services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - FAST_REFRESH=false # Source: https://stackoverflow.com/questions/43274925/development-server-of-create-react-app-does-not-auto-refresh
    volumes:
      - ./client/src:/app/src
  debugger2:
    build:
      context: debugger2
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    volumes:
      - ./debugger2/src:/app/src
