version: '3.8'
services:
  client:
    build:
      context: visualiser
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - FAST_REFRESH=false # Source: https://stackoverflow.com/questions/43274925/development-server-of-create-react-app-does-not-auto-refresh
    volumes:
      - ./visualiser:/app/src
  debugger:
    build:
      context: debugger
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./debugger/src:/app/src
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./server/src:/app/src
