name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Lint
        working-directory: ./client
        run: npm run lint
