name: Pre-Merge Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependency
        working-directory: ./client
        run: npm install
      - name: Lint
        working-directory: ./client
        run: npm run lint

